name: Extract RAR

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Install unrar
        run: |
          sudo apt-get update
          sudo apt-get install -y unrar

      - name: Extract RAR
        run: |
          mkdir -p extracted
          unrar x -o+ "myfile.rar" extracted/

      - name: Show extracted files
        run: |
          ls -lah extracted
